fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: 'v1.0.2'
  symlinks:
    kernel_parameter: "#{source_dir}"
