name    'treydock-kernel_parameter'
version '0.0.1'
source 'git://github.com/treydock/puppet-kernel_parameter.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'kernel_parameter module'
description 'kernel_parameter module'
project_page 'http://github.com/treydock/puppet-kernel_parameter'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'domcleal/augeasproviders, '>= 1.0.2'
